xterm -geometry 100x10+700+400 -T Notary -e 'cd "/Users/Lolo/git/insurance-cordapp/build/nodes/Notary" ; "/Library/Java/JavaVirtualMachines/jdk1.8.0_191.jdk/Contents/Home/jre/bin/java" "-Dname=Notary-corda.jar" "-Dcapsule.jvm.args=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5005 -javaagent:drivers/jolokia-jvm-1.3.7-agent.jar=port=7005" "-jar" "corda.jar"' &

xterm -geometry 100x25+20+000 -T PartyA -e 'cd "/Users/Lolo/git/insurance-cordapp/build/nodes/PartyA" ; "/Library/Java/JavaVirtualMachines/jdk1.8.0_191.jdk/Contents/Home/jre/bin/java" "-Dname=PartyA-corda.jar" "-Dcapsule.jvm.args=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5006 -javaagent:drivers/jolokia-jvm-1.3.7-agent.jar=port=7006" "-jar" "corda.jar"' &
xterm -geometry 100x25+40+200 -T PartyB -e 'cd "/Users/Lolo/git/insurance-cordapp/build/nodes/PartyB" ; "/Library/Java/JavaVirtualMachines/jdk1.8.0_191.jdk/Contents/Home/jre/bin/java" "-Dname=PartyB-corda.jar" "-Dcapsule.jvm.args=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5010 -javaagent:drivers/jolokia-jvm-1.3.7-agent.jar=port=7010" "-jar" "corda.jar"' &
xterm -geometry 100x25+60+400 -T PartyC -e 'cd "/Users/Lolo/git/insurance-cordapp/build/nodes/PartyC" ; "/Library/Java/JavaVirtualMachines/jdk1.8.0_191.jdk/Contents/Home/jre/bin/java" "-Dname=PartyC-corda.jar" "-Dcapsule.jvm.args=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5008 -javaagent:drivers/jolokia-jvm-1.3.7-agent.jar=port=7008" "-jar" "corda.jar"' &

xterm -geometry 100x10+700+000 -T WebPartyA -e 'cd "/Users/Lolo/git/insurance-cordapp/build/nodes/PartyA" ; "/Library/Java/JavaVirtualMachines/jdk1.8.0_191.jdk/Contents/Home/jre/bin/java" "-Dname=PartyA-corda-webserver.jar" "-Dcapsule.jvm.args=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5007 -javaagent:drivers/jolokia-jvm-1.3.7-agent.jar=port=7007" "-jar" "corda-webserver.jar" && exit' &
xterm -geometry 100x10+700+100 -T WebPartyB -e 'cd "/Users/Lolo/git/insurance-cordapp/build/nodes/PartyB" ; "/Library/Java/JavaVirtualMachines/jdk1.8.0_191.jdk/Contents/Home/jre/bin/java" "-Dname=PartyB-corda-webserver.jar" "-Dcapsule.jvm.args=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5011 -javaagent:drivers/jolokia-jvm-1.3.7-agent.jar=port=7011" "-jar" "corda-webserver.jar" && exit' &
xterm -geometry 100x10+700+200 -T WebPartyC -e 'cd "/Users/Lolo/git/insurance-cordapp/build/nodes/PartyC" ; "/Library/Java/JavaVirtualMachines/jdk1.8.0_191.jdk/Contents/Home/jre/bin/java" "-Dname=PartyC-corda-webserver.jar" "-Dcapsule.jvm.args=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5009 -javaagent:drivers/jolokia-jvm-1.3.7-agent.jar=port=7009" "-jar" "corda-webserver.jar" && exit' &

